import { Metadata } from "next";
import "./globals.css"
import { ErrorWrapper } from "./error-wrapper";

export const metadata: Metadata = {
  title: {
    default: "Learn Next JS",
    template: "%s | Balala Template",
    absolute: ""
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header className="bg-slate-800 text-lg text-center w-full p-5 text-white">
          Header
        </header>
        <ErrorWrapper >{children}</ErrorWrapper>
        <footer className="bg-slate-800 text-lg text-center w-full p-5 text-white">
          Footer
        </footer>
      </body>
    </html>
  );
}
