export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header className="w-full p-5 bg-slate-600 text-center">
          <h1>Header</h1>
        </header>
        <main>
          {children}
        </main>
        <footer className="w-full p-5 bg-slate-600 text-center">
          <h1>Footer</h1>
        </footer>
      </body>
    </html>
  )
}
