import { Metadata } from "next"
import "../globals.css"

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <h1 className="text-4xl">Kata-kata hari ini</h1>
        {children}
      </body>
    </html>
  )
}
